---
- hosts: localhost
  tasks:
    #deploy cluster
    - name: delete directory for cluster ansible-container
      file: path=/tmp/galera state=absent

    - name: create directory for cluster ansible-container
      file: path=/tmp/galera state=directory

    - name: init cluster ansible-container
      shell: "ansible-container init"
      args:
        chdir: /tmp/galera

    - name: write container.yml for cluster ansible-container with {{ containers }} containers
      template: src=templates/cluster-container.j2 dest=/tmp/galera/ansible/container.yml

    - name: write main.yml for cluster ansible-container
      template: src=templates/cluster-main.j2 dest=/tmp/galera/ansible/main.yml
    
    - name: write requirements.yml for cluster ansible-container
      template: src=templates/requirements.j2 dest=/tmp/galera/ansible/requirements.yml

    - name: build cluster ansible-container
      shell: "ansible-container build"
      args:
        chdir: /tmp/galera

    - name: ship cluster ansible-container
      shell: "ansible-container shipit openshift --local-images"
      args:
        chdir: /tmp/galera

    - name: play cluster ansible-container
      shell: "ansible-playbook ansible/shipit-openshift.yml"
      args:
        chdir: /tmp/galera
