---
- hosts: localhost
  vars:
    task: "{{ lookup('env','TASK') }}"
    containers: "{{ lookup('env','CLUSTER_SIZE') | int }}"
    token: "{{ lookup('env','TOKEN') }}"
  tasks:
    - include: "{{ task }}.yml"
      static: no
 
#   - name: run {{ task }} with {{ containers }} containers
#     command: ansible-playbook "{{ task }}.yml" "-e" '{"containers"{{':'}} {{ containers }} }' "-e" '{"token"{{':'}} {{ token }} }' "-e" '{"task"{{':'}} {{ task  }} }'
#     when: task == "deploy-cluster"

   #- name: run {{ task }} to {{ containers }} containers
#     command: ansible-playbook "{{ task }}.yml" "-e" '{"containers"{{':'}} {{ containers }} }' "-e" '{"token"{{':'}} {{ token }} }' "-e" '{"task"{{':'}} {{ task  }} }'
#
#   - name: run {{ task }} cluster
#     command: ansible-playbook "{{ task }}.yml"
#     when: task == "heal"
