---
- hosts: localhost
  vars:
    containers: "{{ lookup('env','CLUSTER_SIZE') | int }}"
    namespace: "{{ lookup('env','NAMESPACE') | default('galera', true) }}"
    mariadb_database: "{{ lookup('env','MARIADB_DATABASE') | default('mysql', true) }}"
    mariadb_password: "{{ lookup('env','MARIADB_PASSWORD') | default('foo', true) }}"
    mariadb_root_password: "{{ lookup('env','MARIADB_ROOT_PASSWORD') | default('sesame', true) }}"
    mariadb_username: "{{ lookup('env','MARIADB_USERNAME') | default('admin', true) }}"
    server_url: "{{ lookup('env','OPENSHIFT_SERVER_URL') | default('https://10.1.2.2:8443', true) }}"
    task: "{{ lookup('env','TASK') }}"
    token: "{{ lookup('env','TOKEN') }}"
  tasks:
    - include: "{{ task }}.yml"
      static: no
