---
- hosts: localhost
  vars:
    containers: "{{ lookup('env','CLUSTER_SIZE') | int }}"
    task: "{{ lookup('env','TASK') }}"
    token: "{{ lookup('env','TOKEN') }}"
  tasks:
    - include: "{{ task }}.yml"
      static: no
