apiVersion: v1
kind: Service
metadata:
  labels:
    app: galera
    service: mariadb-{{ item }}
  name: mariadb-{{ item }}
spec:
  ports:
  - name: port-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: port-4567
    port: 4567
    protocol: TCP
    targetPort: 4567
  - name: port-4567-udp
    port: 4567
    protocol: UDP
    targetPort: 4567
  - name: port-4444
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: port-4568
    port: 4568
    protocol: TCP
    targetPort: 4568
  selector:
    app: galera
    service: mariadb-{{ item }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
